### ISSUE TITLE
R.Project package will not be able to find old versions

### ISSUE THREAD

**Issue by farvour** [AdmiringWorm/chocolatey-packages#12]
The chocolatey package for R.Project is going to be unable to find old versions of the packages since the base URL used to locate them changes when a new release occurs.

They get moved to: https://cran.r-project.org/bin/windows/base/old/

Wondering if a simple check to find the requested version under the main path would be good enough and then fall back to `/old/` to try there if it wasn't found in latest.

**Comment by AdmiringWorm** [comment]
Since version 3.3.2 the installer have been embedded inside the package, making this issue irrelevant.
That was the first version released after I was made an maintainer of the package.
Any versions older than that won't be updated, and as such is unsupported.

If you absolutely need an older version, then you will need to buy a license for chocolatey, and make use of the CDN.

**Comment by farvour** [comment]
I'm not quite sure I understand how the issue is no longer relevant. If I want to install 3.3.2, instead of 3.4.3, the download code is still going to try and look for 3.3.2 in the base URI without the `/old/` path on it. Would you prefer I submit a fix to this power shell script that can do the quick check? Using the CDN is not necessary since cran.r-project.org *still hosts the files*, they're just in another location.

**Comment by AdmiringWorm** [comment]
> If I want to install 3.3.2, instead of 3.4.3, the download code is still going to try and look for 3.3.2 in the base URI without the /old/ path on it.

No it won't, after the package itself have been downloaded from chocolatey.org, it never reaches out to any website at all.
As I said, the binary is embedded inside the package and is always available when the package have been downloaded.

**Comment by farvour** [comment]
Understood. So during submission time / build time to chocolatey, choco is hosting the binary file inside of the nuget package. I guess I was trying to compare 3.2.1 stuff and shouldn't have been. Thank you for the clarification. I'm kind of new to the way Chocolatey operates with embedded binaries and such.

**Comment by AdmiringWorm** [comment]
> So during submission time / build time to chocolatey, choco is hosting the binary file inside of the nuget package.

Exactly.

> I guess I was trying to compare 3.2.1 stuff and shouldn't have been.

I thought perhaps something like that was the case, which is also why I mentioned (`Since version 3.3.2 `) previously.

> I'm kind of new to the way Chocolatey operates with embedded binaries and such.

It's not really a new way, just that not many maintainers make use of embedded binaries.
Although, using embedded binaries is recommended when the license of the software allows such a thing.


NOTE:
Feel free to let me know if you discover any bugs in the package, as I'm not using the software myself I most likely won't catch them until I've been notified of them.
