### ISSUE TITLE
(MediathekView) Re-Enable package updates

### ISSUE THREAD

**Issue by phihub** [AdmiringWorm/chocolatey-packages#124]
There is a new Version 13.5.0 available.

Also: It does not depend on Java anymore.

**Comment by AdmiringWorm** [comment]
> There is a new Version 13.5.0 available.

The update had been disabled temporarily due to me not having the time to investigate the requirement of an updated java version (see issue #103), although that is no longer needed.

> Also: It does not depend on Java anymore.

Not entirely true, it still depend on java. The only difference is that it is now included in their zip archives.
TBH, in my mind the package should still have a dependency on one of the java editions, but remove the embedded java installation. But I will think about that before enabling updates again.

I hope to be able to look into this a little more later in the week.

**Comment by AdmiringWorm** [comment]
THe package updates have now been re-enabled.

I have not removed the dependency on java, as I am using the archive they provide on github that do not include java inside of it.

The dependency have been changed to use `adoptopenjdkjre` instead of the commercial java runtime.

**Comment by AdmiringWorm** [comment]
@allcontributors-bot please add @phihub to ideas
