### ISSUE TITLE
Qt Creator currently installed without MSVC debugger support

### ISSUE THREAD

**Issue by jamesg-nz** [AdmiringWorm/chocolatey-packages#216]
IDE isn't so useful for development without working debugger integration.

Only the qtcreator.7z archive is installed from https://download.qt.io/official_releases/qtcreator/4.12/4.12.0/installer_source/windows_msvc2017_x64/

Need to install qtcreatorcdbext.7z archive to get CDB debugger integration (Microsoft debugger installed with MSVC toolchain).

Get error message about missing qtcreatorcdbext.dll file when you go to debug otherwise.

They're separated out because of included Python pieces which is different license to Qt:
https://bugreports.qt.io/browse/QTBUG-65321

**Comment by michaelweghorn** [comment]
Should the CDB extension go to a separate Chocolatey package or become part of the "main" qtcreator package?

**Comment by AdmiringWorm** [comment]
Sorry, I thought I had already commented on this issue.

TBH, I never added the installation of the MSVC debugger to the install script, due to the package should only install qtcreator itself, not any additional software (yes the MSVC debugger would be additional software).

@michaelweghorn makes a good point here with asking if it should go as a separate package, and I would agree with this would be the appropriate approach.

Especially as you mentioned in the last line:
> They're separated out because of included Python pieces which is different license to Qt

**Comment by AdmiringWorm** [comment]
Thanks to @michaelweghorn that provided a new package for this request.
The package will be pushed within the next few days after I have verified it in a VM.

**Comment by AdmiringWorm** [comment]
A package called [qtcreator-cdbext](https://chocolatey.org/packages/qtcreator-cdbext/4.13.2) that adds the debugger have been pushed to chocolatey.
There will most likely be a while until it gets approved for normal consumption. Still, it can be installed by running `choco install qtcreator-cdbext --version 4.13.2` (do this on your own risk though, if a moderator request a change you will not get the updated package unless you remove and reinstall the same version).

**Comment by AdmiringWorm** [comment]
@all-contributors add @jamesg-nz for ideas
