### ISSUE TITLE
Need your help with nionshare package

### ISSUE THREAD

**Issue by hekcyc** [AdmiringWorm/chocolatey-packages#283]
Sorry for opening this as bug report, how can I run OnionShare that I downloaded using Chocolatey? I only can use command lines, no GUI

**Comment by AdmiringWorm** [comment]
How would you run it if you had installed it manually?
The package is just a basic wrapper around the installer of the software, so the way you would run it after manually installing it would be the same way with the package.

I can not give you a straight answer, unfortunately, due to not being familiar with the software (I just created the package as part of a request for one to be created).

What I can tell you though, is that the software gets installed to `C:\Program Files (x86)\OnionShare`, but is not made available on `PATH`.

**Comment by hekcyc** [comment]
haha I make my question a bit wrong, but the thing is that im doing an application that uses Onionshare for upload files, everything is done in a script, that is the need of running without a graphical interface. This program comes with another called AutoKey when I download it in Chocolatey, i think that I will need to work with these together do do it.

Anyway, can you upload the Portable version of AxCrypt in the Chocolatey? 
The link: https://www.axcrypt.net/pt/download/
> AxCrypt 2 standalone / portable version for Windows

**Comment by AdmiringWorm** [comment]
> This program comes with another called AutoKey when I download it in Chocolatey, i think that I will need to work with these together do do it.

If it is part of the program, that too should be available in the installation folder (as referenced in my previous comment).

> Anyway, can you upload the Portable version of AxCrypt in the Chocolatey?
> The link: axcrypt.net/pt/download

> AxCrypt 2 standalone / portable version for Windows

That would be a request for a new package, and I am not the maintainer of the install package for axcrypt.
I suggest either to reach out to the maintainer of the install package (https://chocolatey.org/packages/axcrypt) and ask if he/she is willing to create one, or create a new issue over at https://github.com/chocolatey-community/chocolatey-package-requests) to request one.

**Comment by JourneyOver** [comment]
Was going to say that I would look into making a package for axcrypt portable since I am the maintainer of the axcrypt package, but the portable version link you gave seems to no longer exist (they recently updated their site and a lot of links are still set to under maintenance) and I can no longer find a portable version anywhere.
