### ISSUE TITLE
(nordvpn) Don't launch after install/upgrade

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [AdmiringWorm/chocolatey-packages#298]
**Is your feature request related to a problem? Please describe.**

I don't like having the NordVPN window pop up when I am running upgrades.

**Describe the solution you'd like**

For NordVPN to not start after upgrade/install.

**Describe alternatives you've considered**

N/A

**Additional context**

I haven't dug into the installer, it is possible they have a flag to disable starting after install. Otherwise, `Remove-Process` probably would work.

**Comment by AdmiringWorm** [comment]
Unfortunately, the installer do not include any flags to disable the launching of nordvpn (or at least didn't last time I checked).

I am also a bit hesitant to blindly closing the program/process due to the nature of the program, and due to a certain feature available in nordvpn.

1. Since this is a VPN program, it is more likely that a user wishes to have the program running after installation/upgrading.
2. Since NordVPN have a feature called `KillSwitch` (I think that was the name), this can cause issues on a users computer if the program never isn't kept running after installation. It would mean that the user can not connect to the internet after upgrading.

With that said though, there is a possibility that something can be included if the program didn't run before trying to upgrade NordVPN and is something I could look at. But not yet had the chance to look into this yet.

**Comment by TheCakeIsNaOH** [comment]
Fair enough on the not wanting to blindly close.

It should be doable to do a `Get-Process` before install to check if it is running, and after install do `Remove-Process` if it was not previously running.

**Comment by AdmiringWorm** [comment]
I am thinking.

1. In chocolateyBeforeModify, add a small metafile (basically a small file with basic information for the future) in the temp directory if the program is already launched.
2. If the metafile does not exist, remove/close the nordvpn process
3. Remember to remove the metafile.

That isn't something I have tested if it would work as expected yet though.

**Comment by AdmiringWorm** [comment]
NordVPN will be dropped from this repository, see RFM request: https://github.com/chocolatey-community/chocolatey-package-requests/issues/1454
