### ISSUE TITLE
Nagstamon now hosted on nagstamon.de and github.com

### ISSUE THREAD

**Issue by HenriWahl** [AdmiringWorm/chocolatey-packages#315]
**Describe the bug**
The URLs for Nagstamon are changing.

**To Reproduce**
In the future the redirects now set on nagstamon.ifw-dresden.de might not work anymore.

**Expected behavior**
URLs should work.

**Additional context**
Better change site URL to https://nagstamon.de and download URLs to the current versions on github com to the ones found at https://github.com/HenriWahl/Nagstamon/releases/tag/3.4.1 - will change with every version, e.g. the expected next one 3.6 will be https://github.com/HenriWahl/Nagstamon/releases/tag/3.6.

Thanks anyway for packaging this! :+1:

**Comment by AdmiringWorm** [comment]
Thanks for opening the issue. I was aware there had been changes (due to the updater started failing).
To get it updated is on my TODO list, and I expect to have time to make any necessary changes before easter ends (before Tuesday, in other words).

As the package is embedded, it is generally not a problem that the website and download links changed.

**Comment by HenriWahl** [comment]
Thanks!

**Comment by AdmiringWorm** [comment]
Let's keep the issue open, as I haven't yet made the necessary changes.
I'll close the issue when the changes have been implemented.

**Comment by AdmiringWorm** [comment]
Changes is now implemented, and any new release should be picked up.

**Comment by HenriWahl** [comment]
:+1:
