### ISSUE TITLE
(cmdermini) Change default install location

### ISSUE THREAD

**Issue by jansohn** [AdmiringWorm/chocolatey-packages#45]
**Is your feature request related to a problem? Please describe.**
`cmdermini` is installed to `Get-ToolsLocation` (by default `C:\tools`). I don't see any reason why the package cannot be installed to the default chocolatey install location `C:\ProgramData\Chocolatey`.

**Describe the solution you'd like**
Install `cmdermini` to the default chocolatey install location `C:\ProgramData\Chocolatey`. Maybe provide an additional install parameter to be able to change the install location.

**Comment by AdmiringWorm** [comment]
I don't really see the benefit of changing the install directory to the library directory.

But let me tell you why I decided to continue using the Tools directory.
1. To not making a breaking change to users that already have the package installed, and (*maybe*) expect it already to be there.
2. Because the archive contains a Configuration file that can be changed by the user, now if changing the install directory to `C:\ProgramData\Chocolatey` as you suggest. Then this would lock down the path to administrators only, which wouldn't allow anyone else to change the configurations.

With that said though, if you could enlighten me on **why** you feel it would be best to install to the `C:\ProgramData\Chocolatey` directory, I may take that under consideration.

**Comment by jansohn** [comment]
OK, I can live with changing that environment variable.
