### ISSUE TITLE
Current Authy Desktop version is 1.1.0

### ISSUE THREAD

**Issue by ericbn** [AdmiringWorm/chocolatey-packages#5]
Any guide on how can we update the package code locally, test, and submit a PR for a new version (something on the lines of [homebrew](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) maybe)?

Authy Desktop version is outdated, current one is 1.1.0

**Comment by AdmiringWorm** [comment]
I don't have any guides available for that right now.
But it's relatively simple, first install the AU module (recommended to build directly from the au repository, as that is what's used in this repo).
https://github.com/majkinetor/au

Then after that is done, just run from powerhell in the root of this repo `.\test_all.ps1 nameOfThePackage`

All update checks are run using the `update.ps1` file located in the package folder (not pushed to chocolatey), and for this package I use the redirected download url that they provide for the desktop version which still reports version: 1.0.13.
I don't know, if that is a mistake from them though, or not.

**Comment by AdmiringWorm** [comment]
hmm, seems like they don't update the url that they used for previous versions to the correct version anymore.
I'll need to look into this

**Comment by AdmiringWorm** [comment]
I just updated the update script now, and a new version of authy-desktop should be pushed to chocolatey.org soon.

Please open a separate issue for detailing how you can contribute to this repo.

**Comment by ericbn** [comment]
Thank you, @AdmiringWorm. I'll check https://github.com/majkinetor/au as you recommended.

**Comment by AdmiringWorm** [comment]
It isn't that I just recommend it, but since this repository makes use of au it's required.

Most of the packages I have in this repository is checked on a schedule (twice a day, if I remember correctly) by making use of AU. BTW, AU requires PowerShell v5, so make sure you have that installed.

To test the packages themselves though, I usually expect that all packages modified have been tested in the [chocolatey-test environment][cte]. But that is a general recommendation to use whenever testing packages that are to be submitted to chocolatey.org

Anyways, thanks for letting me know that my update script had stopped working 😄 

[cte]: https://github.com/chocolatey/chocolatey-test-environment
